- name: Authenticate with Google Cloud
  env:
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  run: |
    echo "$GOOGLE_APPLICATION_CREDENTIALS" > key.json
    gcloud auth activate-service-account --key-file=key.json
